### ISSUE TITLE
Publish site not working sometimes

### ISSUE THREAD

**Issue by suresh-kumarp** [salesforcecli/plugin-community#522]
### Summary

We are using GitHub action to publish our custom sites, but it randomly fails with the below error. Please help us to resolve this issue.

![image](https://github.com/salesforcecli/plugin-community/assets/68844099/a26d7264-dfa1-41df-9b0b-494515f7d21a)

The below output is from the same workflow that was run just before the error one.

![image](https://github.com/salesforcecli/plugin-community/assets/68844099/b72986fb-e40e-467f-9a77-573ea3ac6ebf)

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

sf community publish --name 'site name' should publish the site the without any issue

### Actual result

Installing plugin community@3.0.5... yarn add v1.22.19
Installing plugin community@3.0.5... [1/4] Resolving packages...Installing plugin community@3.0.5... [2/4] Fetching packages...Installing plugin community@3.0.5... [3/4] Linking dependencies...Installing plugin community@3.0.5... [4/4] Building fresh packages...Installing plugin community@3.0.5... success Saved lockfile.Installing plugin community@3.0.5... success Saved 46 new dependencies.Installing plugin community@3.0.5... info Direct dependenciesInstalling plugin community@3.0.5... └─ @salesforce/plugin-community@3.0.5Installing plugin community@3.0.5... ├─ fast-redact@3.3.0Installing plugin community@3.0.5... ├─ joycon@3.1.1Installing plugin community@3.0.5... ├─ process-warning@2.3.2Installing plugin community@3.0.5... └─ wcwidth@1.0.1Installing plugin community@3.0.5... Done in 8.62s.Installing plugin community@3.0.5... Refreshing user plugins...Installing plugin community@3.0.5... installed v3.0.5
{
  "code": 1,
  "context": "CommunityPublishCommand",
  "commandName": "CommunityPublishCommand",
  "message": "The requested resource does not exist",
  "name": "NOT_FOUND",
  "status": 1,
  "stack": "NOT_FOUND: The requested resource does not exist\n    at HttpApi.getError (/home/runner/.local/share/sf/node_modules/@salesforce/plugin-community/node_modules/jsforce/lib/http-api.js:252:[12](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7258672427/job/19774747653#step:19:13))\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/runner/.local/share/sf/node_modules/@salesforce/plugin-community/node_modules/jsforce/lib/http-api.js:122:23\n    at async CommunityPublishCommand._run (/home/runner/.local/share/sf/node_modules/@salesforce/plugin-community/node_modules/@oclif/core/lib/command.js:304:22)\n    at async Config.runCommand (/opt/hostedtoolcache/node/20.10.0/x64/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:417:25)\n    at async run (/opt/hostedtoolcache/node/20.10.0/x64/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:85:[16](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7258672427/job/19774747653#step:19:17))",
  "exitCode": 1,
  "warnings": []
}

Error: Process completed with exit code 1.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**: @salesforce/cli/2.21.8 linux-x64 node-v20.10.0

**OS and version**: Ubuntu-22.0  LTS

**Comment by suresh-kumarp** [comment]
@iowillhoit - Please help me on this issue.

**Comment by cristiand391** [comment]
Sorry for the late reply, if you still experience this please open a new issue in this repo:
https://github.com/forcedotcom/cli/issues
